<<<<<<< HEAD
inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
=======
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
>>>>>>> cfca589edaad99ca5b401593d0f307255d337c04
  Enabled: false
